Binding autosave to page unload so it only happens once.
deadcity/charsys pull request #264
Opened 2016-09-19 16:15 UTC by eliilek

Per Stephanie I am making a pull request! Hooray! That said someone who's not on windows should probably test this.

2016-09-19 16:17 UTC, eliilek commented
I screwed up a thing hang on, sorry.

2016-09-19 16:29 UTC, stephmarx commented on app/views/characters/edit.slim
> +		//$('form input, form textarea, form select').on('blur', function () {
Remove commented out code.

2016-09-19 16:30 UTC, sublimemarch requested changes

2016-09-20 03:40 UTC, stephmarx commented
Nope, this doesn't solve the issue.

![screen shot 2016-09-19 at 10 40 44 pm](https://cloud.githubusercontent.com/assets/9502152/18656818/2080b31c-7eba-11e6-8431-ea83ca50e5c9.png)

2016-09-20 03:45 UTC, cmho commented
I think part of the continuing issue might be that submitting the form also triggers unload, so the elements are definitely submitted at least twice. Might need to unbind it on the submit event.  (That doesn't explain why steph is still getting it a huge number of times—after I pulled this branch it only duplicates the new stuff once—but might help, anyway.)

2016-09-21 13:19 UTC, stephmarx commented
It works! Hurray!

2016-09-21 13:19 UTC, sublimemarch approved these changes

2016-09-21 13:19 UTC, merged